shiro:
  ws:
    client:
      enable: true
      url: ${dev.ws.clientUrl}
    access-token: ${dev.token}
per:
  file-location: ${dev.file-location}
  video-location: ${dev.video-location}
  python:
    path: ${dev.python.path}
  jm:
    img-path: ${dev.img-path}
  bot:
    owner: 825352674
  listener:
    impl: Shiro
    package: per.chowh

server:
  port: 8002

spring:
  profiles:
    active: dev
  datasource:
#    url: jdbc:mysql://${dev.server-ip}:3306/chowh_bot?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:sqlite:bot.db
#    username: ${dev.database.username}
#    password: ${dev.database.password}
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  cache:
    jcache:
      config: classpath:ehcache.xml
    type: jcache
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto